spring:
  thymeleaf:
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    cache: false
    mode: HTML
    suffix: .html

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    platform: h2

  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true



